import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "zod";
import { complexityLevels } from "./lib/learning-complexity";

function uniqueIdGlob(options: Parameters<typeof glob>[0]): ReturnType<typeof glob> {
  const loader = glob(options);
  return {
    ...loader,
    name: "unique-id-glob-loader",
    async load(context) {
      const pathsById = new Map<string, string | undefined>();
      const store = new Proxy(context.store, {
        get(target, property) {
          if (property === "set") {
            return (entry: Parameters<typeof target.set>[0]) => {
              const existingPath = pathsById.get(entry.id);
              if (pathsById.has(entry.id) && existingPath !== entry.filePath) {
                throw new Error(
                  `Duplicate sheet ID "${entry.id}" generated by ${existingPath} and ${entry.filePath}`,
                );
              }
              pathsById.set(entry.id, entry.filePath);
              return target.set(entry);
            };
          }
          const value = Reflect.get(target, property, target);
          return typeof value === "function" ? value.bind(target) : value;
        },
      });
      await loader.load({ ...context, store });
    },
  };
}

const sheetReference = z.union([
  z.string(),
  z.object({
    id: z.string(),
    planned: z.literal(true),
  }),
]);

const sheet = defineCollection({
  loader: uniqueIdGlob({ pattern: "**/*.{md,mdx}", base: "./src/content/sheets" }),
  schema: z.object({
    title: z.string(),
    summary: z.string(),
    territory: z.enum(["mechanisms", "structures", "failures", "systems"]),
    status: z.enum(["published", "planned"]),
    complexity: z.enum(complexityLevels),
    requires: z.array(sheetReference).default([]),
    introduces: z.array(z.string()).default([]),
    related: z.array(sheetReference).default([]),
    scenarios: z.array(z.string()).default([]),
    terms: z
      .array(z.object({ term: z.string(), definition: z.string() }))
      .default([]),
    references: z
      .array(
        z.object({
          key: z.string(),
          title: z.string(),
          url: z.string().url(),
        }),
      )
      .default([]),
  }),
});

export const collections = { sheet };
